src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;
  
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'El título es obligatorio')]
    private $Title;

    #[ORM\Column(type: "text")]
    #[Assert\NotBlank(message: 'El contenido es obligatorio')]
    private $Content;

    #[ORM\Column(type: "datetime")]
    private $PublishedAt;

    #[ORM\Column(length: 255)]
    private $Image;

    #[ORM\Column(length: 255)]
    private $Slug;

    #[ORM\Column(type: "integer")]
    private $NumLikes;

    #[ORM\Column(type: "integer")]
    private $NumComments;
    
    #[ORM\Column(type: "integer")]
    private $NumViews;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Comment::class)]
    private Collection $comments;

    #[ORM\ManyToOne(inversedBy: 'posts')]
    private ?User $User = null;
    

    public function __construct()
    {
        $this->PublishedAt = new \DateTime();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->PublishedAt;
    }

    public function setPublishedAt(\DateTimeInterface $PublishedAt): self
    {
        $this->PublishedAt = $PublishedAt;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->Slug;
    }

    public function setSlug(string $Slug): self
    {
        $this->Slug = $Slug;

        return $this;
    }

    public function getNumLikes(): ?int
    {
        return $this->NumLikes;
    }

    public function setNumLikes(int $NumLikes): self
    {
        $this->NumLikes = $NumLikes;

        return $this;
    }

    public function getNumComments(): ?string
    {
        return $this->NumComments;
    }

    public function setNumComments(string $NumComments): self
    {
        $this->NumComments = $NumComments;

        return $this;
    }

    public function getNumViews()
    {
        return $this->NumViews;
    }
    public function setNumViews($NumViews)
    {
        $this->NumViews = $NumViews;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): static
    {
        $this->User = $User;

        return $this;
    }

}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use Symfony\Component\Filesystem\Filesystem;
use App\Entity\Comment;
use App\Entity\Post;
use App\Form\CommentFormType;
use App\Form\PostFormType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

class BlogController extends AbstractController
{
    #[Route("/blog/buscar/{page}", name: 'blog_buscar')]
    public function buscar(ManagerRegistry $doctrine,  Request $request, int $page = 1): Response
    {
       $palabra = $request->query->get('searchTerm', ''); 
       $repositorio = $doctrine->getRepository(Post::class);
       $posts = $repositorio->findByTextPaginated($page, $palabra);
       $recentPosts = $repositorio->findRecents();
       return $this->render('blog/blog.html.twig', ['posts'=> $posts, 'recents'=>$recentPosts]);
    } 
   
    #[Route("/blog/new", name: 'new_post')]
    public function newPost(ManagerRegistry $doctrine, Request $request, SluggerInterface $slugger): Response
    {
        $post = new Post();
        $form = $this->createForm(PostFormType::class, $post);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $file = $form->get('Image')->getData();
            if ($file) {
                $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$file->guessExtension();
        
                // Move the file to the directory where images are stored
                try {
        
                    $file->move(
                        $this->getParameter('images_directory'), $newFilename
                    );
                    $filesystem = new Filesystem();
                    $filesystem->copy(
                        $this->getParameter('images_directory') . '/'. $newFilename,
                        $this->getParameter('portfolio_directory') . '/'.  $newFilename, true);
        
                } catch (FileException $e) {
            
                }
                $post->setImage($newFilename);
            }  
            $repositorio = $doctrine->getRepository(Post::class);
            $slugExistente = $repositorio->findOneBy(['Slug' => $slugger->slug($post->getTitle())]);
            $post = $form->getData();
            $post->setUser($this->getUser());
            if($slugExistente) {
                $post->setSlug($slugger->slug($post->getTitle() . rand(0, 1000)));    
            } else {
                $post->setSlug($slugger->slug($post->getTitle()));
            }
            $post->setNumLikes(0);
            $post->setNumComments(0);
            $post->setNumViews(0);
            $entityManager = $doctrine->getManager();
            $entityManager->persist($post);
            $entityManager->flush();
            return $this->redirectToRoute('blog', []);
        }
        return $this->render('blog/new_post.html.twig', ['form' => $form->createView()]);
    }
    
    #[Route("/single_post/{slug}/like", name: 'post_like')]
    public function like(ManagerRegistry $doctrine, $slug): Response
    {   
        $repositorio = $doctrine->getRepository(Post::class);
        $post = $repositorio->findOneBy(['Slug' => $slug]);
        $post->setNumLikes($post->getNumLikes() + 1);
        $entityManager = $doctrine->getManager();
        $entityManager->persist($post);
        $entityManager->flush();
        return $this->redirectToRoute('single_post', ['slug'=> $slug]);
    }

    #[Route("/blog/{page}", name: 'blog')]
    public function index(ManagerRegistry $doctrine, int $page = 1): Response
    {
        $repository = $doctrine->getRepository(Post::class);
        $posts = $repository->findAllPaginated($page);
        $recentPosts = $repository->findRecents();
        
        return $this->render('blog/blog.html.twig', [
            'posts' => $posts, 'recents' => $recentPosts
        ]);
    }

    #[Route("/single_post/{slug}", name: 'single_post')]
    public function post(ManagerRegistry $doctrine, Request $request, $slug): Response
    {
        $repository = $doctrine->getRepository(Post::class);
        $post = $repository->findOneBy(["Slug"=>$slug]);
        $recentPosts = $repository->findRecents();
        $comment = new Comment();
        $form = $this->createForm(CommentFormType::class, $comment);
        $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                $comment = $form->getData();
                $comment->setPost($post);  
                $post->setNumComments($post->getNumComments() + 1);
                $entityManager = $doctrine->getManager();    
                $entityManager->persist($comment);
                $entityManager->flush();
                return $this->redirectToRoute('single_post', ["slug" => $post->getSlug()]);
    }

        return $this->render('blog/single_post.html.twig', ['post' => $post, 'recents' => $recentPosts, 'commentForm'=>$form->createView()]);
    }
}

templates/blog/blog.html.twig
{% extends 'base.html.twig' %}
{% block title %}Blog
{% endblock %}
{% block body %}
	<!-- Principal Content Start -->
	<div id="blog">
		<div class="container">
			<div
				class="row">

				<!-- Blocks of Posts -->
				<div class="col-xs-12 col-sm-8 row">
					{% if posts %}
						{% for post in posts.results %}
							{{include ('partials/post.html.twig', {'post':post})}}
						{% endfor %}
					{% else %}
						<p>No se han encontrado posts
							{{texto}}</p>
					{% endif %}
					{% if posts.hasToPaginate %}
						<div class="text-left">
							<ul class="pagination">
								{% if posts.hasPreviousPage %}
									<li class="prev">
										<a href="{{ path('blog', {page: posts.previousPage}) }}" rel="previous">
											<i class="fa fw fa-long-arrow-left"></i>
											Previous</a>
									</li>
								{% else %}
									<li class="prev disabled">
										<span>
											<i class="fa fw fa-arrow-left"></i>
											Previous
										</span>
									</li>
								{% endif %}

								{% for i in 1..posts.lastPage %}
									{% if i == posts.currentPage %}
										<li class="active">
											<span>{{ i }}</span>
										</li>
									{% else %}
										<li>
											<a href="{{ path('blog', {page: i}) }}">{{ i }}</a>
										</li>
									{% endif %}
								{% endfor %}

								{% if posts.hasNextPage %}
									<li class="next">
										<a href="{{ path('blog', {page: posts.nextPage}) }}" rel="next">Next
											<i class="fa fw fa-arrow-right"></i>
										</a>
									</li>
								{% else %}
									<li class="next disabled">
										<span>Next
											<i class="fa fw fa-arrow-right"></i>
										</span>
									</li>
								{% endif %}
							</ul>
						</div>
					{% endif %}

				</div>
				<!-- End of Blog Post -->

				<!-- Side bar -->

				<div class="col-xs-12 col-sm-4">
					<form class="" action='{{ path('blog_buscar') }}'>
						<input type="text" class="form-control" style="display:unset; width:85%" placeholder="Search" name='searchTerm'>
						<button type='submit' class="btn btn-primary btn-danger">
							<i class="fa fa-search"></i>
						</button>
					</form>
					<div class="panel">
						<div class="panel-heading">
							<h4>Categories</h4>
						</div>
						<div class="panel-body">
							<ul class="nav">
								<li>
									<a href="#">Category I</a>
								</li>
								<li>
									<a href="#">Category II</a>
								</li>
								<li>
									<a href="#">Category III</a>
								</li>
								<li>
									<a href="#">Category IV</a>
								</li>
								<li class="last">
									<a href="#">Category V</a>
								</li>
							</ul>
						</div>
					</div>
					<div class="well">
						<h4>Soluta</h4>
						<p>Quod soluta corrupti earum officia vel inventore vitae quidem, consequuntur odit impedit.</p>
					</div>
					<h3>Recent Posts</h3>
					<hr>
					{% if recents %}
						{% for recent in recents %}
							{{include ('partials/recent_post.html.twig', {'recent':recent})}}
						{% endfor %}
					{% else %}
						<p>No se han encontrado posts recientes
							{{texto}}</p>
					{% endif %}
				</div>
				<!-- End of Side bar -->

			</div>
		</div>
	</div>
	<!-- End of Principal Content Start -->

{% endblock %}

templates/blog/new_post.html.twig
{% extends 'base.html.twig' %}
{% block title%}Images{% endblock %}
{% block body%}
<!-- Principal Content Start -->
   <div id="new Post">
   	  <div class="container">
   	    <div class="col-xs-12 col-sm-8 col-sm-push-2">
       	   <h1>New Post</h1>
			   {{ form(form, {'attr': {'class':'form-horizontal'}}) }}
       	   <hr class="divider">
		</div>   
   	  </div>
    </div>
<!-- Principal Content Start -->
{% endblock %}

templates/blog/single_post.html.twig
{% extends 'base.html.twig' %}
{% block title%}Post
{% endblock %}
{% block body%}
	<!-- Principal Content Start -->
	<div id="single">
		<div class="container">
			{% if not post %}
				<h2>Post not found</h2>
			{% else %}
				<!-- Full Article -->
				<div class="row">
					<div class="post-heading">
						<h2>{{post.title}}</h2>
						<img class="img-responsive" src="{{ asset('images/index/gallery/' ~ post.image) }}" alt="{{post.title}}">
					</div>
					<hr class="subtitle">
					<div class=" block1">
						<div class="col-xs-12 col-sm-9">
							<p>
								{{post.content}}
							</p>
							<h4>- By
								{{ post.user.name}}</h4>
							<hr>
							<ul class="list-inline">
								<li>{{ post.publishedAt | date('d') }}
									{{ post.publishedAt | date('F') }}</li>
								{% if app.user %}
									<li>
										<a class="page-scroll" href="#form">COMMENT</a>
										|</li>
									<li>
										<a href="{{ path('post_like', {slug: post.slug}) }}">LIKE</a>
										|<i class="fa fa-heart sr-icons"></i>
										{{post.numLikes}}
										<i class="fa fa-comments sr-icons"></i>
										{{post.numComments}}</li>
								{% else %}
									<li>
										<a class="page-scroll" href="{{path('app_login')}}">COMMENT</a>
										|</li>
									<li>
										<a href="{{path('app_login')}}">LIKE
										</a>
										|
										<i class="fa fa-heart sr-icons"></i>
										{{post.numLikes}}<i class="fa fa-comments sr-icons"></i>
										{{post.numComments}}</li>
								{% endif %}

							</ul>
						</div>
						<div class="col-xs-12 col-sm-3">
							<h4>Recent Post</h4>
							<hr class="subtitle1">
							{% for recent in recents %}
								{{ include ('partials/recent_post.html.twig', {'recent': recent}) }}
							{% endfor %}
						</div>
					</div>
				</div>
				<!-- End of Full Article -->

				<!-- Comments -->
				<div class="row">
					{% if app.user %}
						<div class="col-xs-12 col-sm-12 block2">
							{% for comment in post.comments %}
								{{ include ('partials/comment.html.twig', {'comment': comment}) }}
							{% endfor %}
							<hr class="line">
							{{ include ('partials/form_comment.html.twig') }}
						</div>
					</div>
					
				</div>
					{% else %}
						<div class="col-xs-12 col-sm-12 block2">
							{% for comment in post.comments %}
								{{ include ('partials/comment.html.twig', {'comment': comment}) }}
							{% endfor %}
						</div>
			{% endif %}

			<!-- End of Comments -->
		</div>
	{% endif %}

</div>
<!-- End of Principal Content Start -->{% endblock %}